twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    - 'components/form/fields.html.twig'
  default_path: '%kernel.project_dir%/templates'
  globals:
    admin_email: '%admin_email%'
    app_name: '%app.name%'
    contact_email: '%contact_email%'
    option_service: '@App\Domain\Application\Service\OptionService'

when@test:
  twig:
    strict_variables: true


