version: '3.7'

services:
  database:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: hair_star
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - "8080:80"
    depends_on:
      - database

  maildev:
    hostname: maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "1080:80"
      - "25:25"

volumes:
  db_data: { }
  nginx_logs: { }
