admin_controllers:
  name_prefix: admin_
  prefix: '%admin_prefix%'
  resource: ../../src/Http/Admin/Controller/
  type: attribute

api_controllers:
  name_prefix: api_
  prefix: /api
  resource: ../../src/Http/Api/Controller/
  type: attribute

app_controllers:
  resource: ../../src/Http/Controller/
  type: attribute
  name_prefix: 'app_'