version: '3'

services:
  app:
    image: hair-star-image
    container_name: app
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@database:3306/${DB_DATABASE:-symfony}

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE:-symfony}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}

volumes:
  database_data: