parameters:
  admin_prefix: '%env(resolve:ADMIN_PREFIX)%'
  organizer_prefix: '/dashboard'
  admin_email: '%env(ADMIN_EMAIL)%'
  sender_email: '%env(SENDER_EMAIL)%'
  contact_email: '%env(CONTACT_EMAIL)%'
  app.name: '%env(APP_NAME)%'
  app.email.support: '%env(APP_EMAIL_SUPPORT)%'
  download_path:    '%kernel.project_dir%/downloads'
  videos_path:      '%download_path%/videos'
  sources_path:     '%download_path%/sources'
  public_path: '%kernel.project_dir%/public'
  timezone: 'Europe/Paris'
  realisation_img_dir: '%kernel.project_dir%/public/uploads/images/realisations'
  upload_images_directory: '%kernel.project_dir%/public/uploads/images'
  avatar_images: '/uploads/avatars'

  stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
  stripe_connect_webhook_secret: '%env(STRIPE_CONNECT_WEBHOOK_SECRET)%'
  stripe_public_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
  stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

  image_resize_key: '%env(resolve:IMAGE_RESIZE_KEY)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false
    bind:
      $videosPath: '%videos_path%'
      $adminPrefix: '%admin_prefix%'
      $organizerPrefix: '%organizer_prefix%'
      $publicPath: '%public_path%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

  App\Http\Controller\:
    resource: '../src/Http/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Http\Admin\Controller\:
    resource: '../src/Http/Admin/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Http\Api\Controller\:
    resource: '../src/Http/Api/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Helper\Paginator\PaginatorInterface:
    class: App\Helper\Paginator\KnpPaginator

  App\Helper\MinutesToTimeHelper: ~

  Knp\Bundle\PaginatorBundle\Helper\Processor: ~

  App\Infrastructure\Mailing\MailService:
    arguments:
      $senderEmail: '%sender_email%'
      $senderName: '%app.name%'

  App\Domain\Contact\ContactService:
    arguments:
      $contactEmail: '%contact_email%'

  App\Http\Type\PriceType:
    arguments: [ '@App\Helper\CentToEuroTransformer' ]
    tags: [ 'form.type' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Infrastructure\AppConfigService:
    arguments:
      $appName: '%app.name%'
      $adminEmail: '%admin_email%'

  App\Infrastructure\Image\ImageResizer:
    arguments: [ '%image_resize_key%' ]

  App\Http\Twig\TwigUrlExtension:
    arguments:
      $uploaderHelper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'

  App\Domain\Application\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Infrastructure\Payment\Stripe\StripeApi:
    arguments: [ '%stripe_secret_key%' ]

  App\Infrastructure\Payment\Stripe\StripeEventValueResolver:
    arguments: [ '%stripe_webhook_secret%' ]
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  App\Domain\Payment\PaymentService:
    arguments:
      $processors: [ '@App\Infrastructure\Payment\Stripe\StripePaymentProcessor', '@App\Infrastructure\Payment\Cash\CashPaymentProcessor' ]

  App\Domain\Payment\RefundService:
    arguments:
      $processors: [ '@App\Infrastructure\Payment\Stripe\StripeRefundProcessor', '@App\Infrastructure\Payment\Cash\CashRefundProcessor' ]

  App\Infrastructure\Youtube\YoutubeService:
    arguments:
      $apiKey: '%env(resolve:YOUTUBE_API_KEY)%'
      $youtubeChannelID: '%env(resolve:YOUTUBE_CHANNEL_ID)%'

  _instanceof:
    App\Normalizer\Breadcrumb\BreadcrumbGeneratorInterface:
      tags: [ 'app.breadcrumb' ]

  App\Http\Twig\TwigBreadcrumbExtension:
    arguments: [ !tagged_iterator app.breadcrumb ]

# TODO: Si besoin d'utiliser le nom de l'application en BDD dans les templates, décommenter les lignes ci-dessous
#  App\Domain\Application\EventListener\ConfigListener:
#    tags:
#      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
